---
title: "SEER Thyroid"
author: "Dan Weinberger"
date: '2023-07-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(lubridate)
library(MASS)
library(ggplot2)
```

## Read in Data

```{r}
a1 <- read_excel('./CONFIDENTIAL/SEERThy.23.6.17SEND.xlsx', sheet='Rates x hist x mo', skip=2) %>%
  mutate( date = as.Date(paste(Year, Month, '01', sep='-'), '%Y-%B-%d')) %>%
  rename(monthdays = 'd/mo', Outcome=Count) %>%
  select( Histology,date, Outcome, Population,monthdays ) %>%
    mutate(log_offset= log(Population/monthdays*30.3)) %>%
  arrange(Histology, date) 
```
```{r}
b1 <- a1 %>%
  filter(Histology == 'Papillary') %>%
  arrange(date) %>%
  mutate(index=row_number())

set.start.date =as.Date('2020-03-01')

form1a <- ' ~ index + offset(log_offset)'
outcome <- 'Outcome_pre '
form1 <- paste0(outcome, form1a)

mod1 <- RunControl(ds=b1 ,set.start.date=set.start.date, set.form_cont1=form1)

out1 <-  OutputsControl(fitted.mod=mod1, niter=10000)
```

```{r}
out1$p.rr.trend
```

```{r}
out1$p.preds
```

```{r}
out1$p.cum_prevented
```


